### ISSUE TITLE
hooks-schema-validation.ipynb actions UI image broken

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS-samples#114]
![image](https://github.com/treeverse/lakeFS-samples/assets/3787958/ed450303-92de-4238-a45f-d84ab69b4c51)

**Comment by rmoff** [comment]
@N-o-Z what were you using to view the notebook? I think Jupyter must be more forgiving because it was fine the with the `./Images` for accessing `./images` on disk.

**Comment by N-o-Z** [comment]
> @N-o-Z what were you using to view the notebook? I think Jupyter must be more forgiving because it was fine the with the `./Images` for accessing `./images` on disk.

Viewed it from the notebook deployed by the docker compose
