### ISSUE TITLE
lakeFS samples- make cloud/own-storage default much clearer

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakeFS-samples#117]
From conversation with @iddoavn and @kesarwam : Can we use use profiles in Docker Compose so that users just do `docker compose up` (and avoid the problem that the Docker desktop app restart the _whole_ stack even if only one container was launched)?

**Comment by kesarwam** [comment]
Yes, profile can solve the problem.

**Comment by rmoff** [comment]
PR: https://github.com/treeverse/lakeFS-samples/pull/118
