### ISSUE TITLE
R notebooks fail with s3saveRDS error "Option seekfunction (20167) has unknown or unsupported type"

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakeFS-samples#132]
Two of the R notebooks have started [failing](https://github.com/treeverse/lakeFS-samples/actions/runs/5875308995):

* `R-weather.ipynb`
* `R-nyc.ipynb`

The error is when calling `s3saveRDS`: 

```R
aws.s3::s3saveRDS(x = nyc_data,
                  object = paste0(branch,"/nyc/","nyc_permits.R"), 
                  bucket = repo_name, 
                  region="",
                  use_https=useHTTPS)
```

```
Error in curl::handle_setopt(handle, .list = req$options): Option seekfunction (20167) has unknown or unsupported type.
Traceback:

1. s3saveRDS(x = df, bucket = "quickstart", object = paste0(branch, 
 .     "/weather/", "data.R"), base_url = baseurl, region = "", 
 .     use_https = FALSE)
2. put_object(file = tmp, bucket = bucket, object = object, ...)
3. s3HTTP(verb = "PUT", bucket = bucket, path = paste0("/", object), 
 .     headers = headers, request_body = file, verbose = verbose, 
 .     show_progress = show_progress, ...)
4. httr::PUT(url, H, body = httr::upload_file(request_body), query = query, 
 .     show_progress, ...)
5. request_perform(req, hu$handle$handle)
6. curl::handle_setopt(handle, .list = req$options)
```

**Comment by rmoff** [comment]
The error comes from `curl` [here](https://github.com/jeroen/curl/blob/master/src/handle.c#L364). I have no idea what it means or why it's happening now. 

Can't reproduce it locally either. Different curl versions??

**Comment by rmoff** [comment]
These notebooks were working fine in these test runs against `main` (the failures were other notebooks): 

* https://github.com/treeverse/lakeFS-samples/actions/runs/5802396382 
* https://github.com/treeverse/lakeFS-samples/actions/runs/5836600984

The notebooks also ran fine in the PR https://github.com/treeverse/lakeFS-samples/actions/runs/5866557042. 

So nothing's been merged to `main` that would account for this failure.

**Comment by rmoff** [comment]
Courtesy of @alexellis I tried out [Actuated](https://github.com/self-actuated/actuated) and got a shell onto the GH runner itself, and an SSH port forward to try out Jupyter

```shell
ssh -L 18888:localhost:8888 -p 35809 runner@<actuated host>
```

From here I ran Jupyter Notebook interactively and `R-nyc.ipynb` **_ran just fine_**

![CleanShot_2023-08-24_at_14 30 16](https://github.com/treeverse/lakeFS-samples/assets/3671582/8b156663-c0b9-472e-ab44-af33db16680a)

---

If the notebook runs ok, on both local and runner environments, then the attention turns to the test itself - papermill. 

Here lies the manifestation of the problem (both local and GH runner): 

```shell
docker exec $(docker ps -q --filter expose=8888) \
              papermill --cwd /home/jovyan/notebooks/ \
                        "/home/jovyan/notebooks/R-nyc.ipynb" \
                        "/home/jovyan/notebooks/papermill-out/R-nyc.ipynb"
Input Notebook:  /home/jovyan/notebooks/R-nyc.ipynb
Output Notebook: /home/jovyan/notebooks/papermill-out/R-nyc.ipynb
Working directory: /home/jovyan/notebooks/
Executing:   0%|          | 0/68 [00:00<?, ?cell/s]Executing notebook with kernel: ir
Executing:  41%|████      | 28/68 [00:01<00:01, 24.06cell/s]
Execution halted
Executing:  46%|████▌     | 31/68 [00:02<00:02, 14.95cell/s]
Traceback (most recent call last):
  File "/opt/conda/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/opt/conda/lib/python3.10/site-packages/papermill/execute.py", line 128, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/opt/conda/lib/python3.10/site-packages/papermill/execute.py", line 232, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError:
---------------------------------------------------------------------------
Exception encountered at "In [15]":
Error in curl::handle_setopt(handle, .list = req$options): Option seekfunction (20167) has unknown or unsupported type.
Traceback:

1. aws.s3::s3saveRDS(x = nyc_data, object = paste0(branch, "/nyc/",
 .     "nyc_permits.R"), bucket = repo_name, region = "", use_https = useHTTPS)
2. put_object(file = tmp, bucket = bucket, object = object, ...)
3. s3HTTP(verb = "PUT", bucket = bucket, path = paste0("/", object),
 .     headers = headers, request_body = file, verbose = verbose,
 .     show_progress = show_progress, ...)
4. httr::PUT(url, H, body = httr::upload_file(request_body), query = query,
 .     show_progress, ...)
5. request_perform(req, hu$handle$handle)
6. curl::handle_setopt(handle, .list = req$options)
```

**Comment by rmoff** [comment]
Looking at the container build logs for executions of the action [when it worked](https://github.com/treeverse/lakeFS-samples/actions/runs/5866557042/job/15905590420) and [when it then didn't](https://github.com/treeverse/lakeFS-samples/actions/runs/5875308995/job/15931388523) I spotted one difference in the R packages: 

r-httr-1.4.6               build    r42hc72bb7e_1
vs
r-httr-1.4.7               build    r42hc72bb7e_0

Looking at the [release log](https://github.com/r-lib/httr/releases/tag/v1.4.7) for [httr](https://github.com/r-lib/httr) I noticed [this commit](https://github.com/r-lib/httr/commit/756505fdce003e3d3bac33691f4b3dcf5e9a4d82#) which includes [`seekfunction`](https://github.com/r-lib/httr/commit/756505fdce003e3d3bac33691f4b3dcf5e9a4d82#diff-eeb9eccdd901fea9f32aa7e3fcb8ac636997c7e88f24f6deac27f53f2f3efbacR28) as named in this error. 

So, something smells fishy - let's hope it's not a red herring … 🐟

**Comment by rmoff** [comment]
Logged an issue on the httr project https://github.com/r-lib/httr/issues/746

**Comment by rmoff** [comment]
Pinning httr to 1.4.6 fixed the notebooks https://github.com/treeverse/lakeFS-samples/pull/136/files#diff-fbb41456a45d9370a30a5529ec28d267198a63f76888ffff2ad7fab4f86fbdc2R31

**Comment by alexellis** [comment]
Glad [actuated](https://actuated.dev) was of help to you @rmoff
