### ISSUE TITLE
Samples Repo - Housekeeping

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakeFS-samples#47]
@adipolak should these three be moved to their own folder in line with the other examples? 
![CleanShot 2023-04-17 at 11 38 13](https://user-images.githubusercontent.com/3671582/232461070-ccb7a394-3f1f-4d06-bd84-148ff0ccd11d.png)

**Comment by adipolak** [comment]
yes! - thanks!  afaik colab was retired. It used to be part of the https://lakefs.io/developers/ page, which linked to google colab.
I wonder if it is possible to transform it into a dedicated sample/folder instructing users how to start their own collab given lakeFS cloud access.
