### ISSUE TITLE
lakeFS-samples: Automagically customise notebook for user's environment

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakeFS-samples#77]
Is there a smooth way to customise the notebooks so that when the user loads Jupyter they are pre-populated with their lakeFS endpoint and credentials? 

This would make the notebooks more friendly for users of lakeFS cloud and local installs of lakeFS. At the moment the notebooks use default values of the lakeFS server that's part of the Docker Compose.

**Comment by rmoff** [comment]
Could move this into its own notebook that users customise and save, and then add it as an include it from all other notebooks? 


![Image](https://github.com/treeverse/lakeFS-samples/assets/3671582/e01ffc92-1006-4ba8-9e1c-67ec226fc5a4)

Or write a shell script that does a `sed` search and replace across the notebooks? 


Default path should be for users who are using the provided lakeFS to not need to change anything.

**Comment by rmoff** [comment]
@iddoavn @kesarwam please review 👆🏻 and let me know what you think.

**Comment by kesarwam** [comment]
@rmoff Good idea but sometime customers download only 1 notebook and run in their existing Juptyer or Databricks environment instead of cloning full lakefs-samples repo.

**Comment by rmoff** [comment]
That's a great point @kesarwam. 

Given that, I'm a bit stumped how to best address this requirement. Unless you or @iddoavn have suggestions then I'm inclined to close it out for now, WDYT?

**Comment by rmoff** [comment]
Closing - feel free to re-open with further discussion/ideas.
